In [1]:
import pandas as pd
import numpy as np

In [6]:
# Create a 1D array from 10 to 50
arr1=np.arange(10,51)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [10]:
# Create a 3x3 array of random numbers between 0 and 1
arr2=np.random.random((3,3))
print(arr2)

[[0.43449598 0.62001688 0.62644782]
 [0.86597635 0.43168947 0.91451409]
 [0.79241042 0.3964599  0.58115536]]


In [14]:
#Find the shape, size, and data type of the array you created in the previous task.
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)

(3, 3)
9
float64


In [15]:
#Add 5 to every element of a 1D array
arr1_5=arr1+5
print(arr1_5)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


In [41]:
#Multiply two 2D arrays element-wise.
a= np.array([2,3,4,5])
b = np.array([3,2,5,6])
result = a*b
print(result)

[ 6  6 20 30]


In [24]:
#first row,last row and first three rows and first two columns
ar=np.arange(1,26).reshape(5,5)
print(ar)
print(ar[0,:])
print(ar[:,-1])
print(ar[:3,:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[1 2 3 4 5]
[ 5 10 15 20 25]
[[ 1  2]
 [ 6  7]
 [11 12]]


In [27]:
random_arr = np.random.randint(1, 101, size=10)
max_value=np.max(random_arr)
print(max_value)
min_value=np.min(random_arr)
print(min_value)
mean_value = np.mean(random_arr)
print(mean_value)
std_dev_value = np.std(random_arr)
print(std_dev_value)

90
4
39.9
26.296197443736993


In [28]:
#Converting a 1D array of numbers from 1 to 12 into a 3x4 matrix.
array_1d = np.arange(1, 13)
print(array_1d)
matrix_3x4 = array_1d.reshape(3, 4)
print(matrix_3x4)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [31]:
#3x3 matrix of ones and Adding a 1D array [1, 2, 3] to each row
matrix_ones = np.ones((3, 3))
array_1d = np.array([0, 1, 2])
result = matrix_ones + array_1d
print(result)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [38]:
#Creating a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
arr = np.arange(1, 51)
div5 = arr[arr % 5 == 0]
print(div5)

[ 5 10 15 20 25 30 35 40 45 50]


In [39]:
#Creating two 2x2 matrices and perform matrix multiplication.
matrix_1 = np.array([[1, 2], [3, 4]])
matrix_2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix_1, matrix_2)
print(result)


[[19 22]
 [43 50]]


In [40]:
#Given a 4x4 array, use fancy indexing to extract the diagonal elements.
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
diagonal_elements = arr[np.arange(4), np.arange(4)]
print(diagonal_elements)

[ 1  6 11 16]
